# This is a basic workflow that is manually triggered

name: Deploy

# Controls when the action will run. Workflow runs when manually triggered using the UI
# or API.
on:
  push:
    tags:
      - "v.*"

  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  semver:
    runs-on: ubuntu-latest
    steps:
      - name: log
        run: |
          echo "Tag name from GITHUB_REF_NAME: $GITHUB_REF_NAME"
          echo "Tag name from github.ref_name: ${{  github.ref_name }}"
          echo version_tag github.ref ${{ github.ref }}

      - name: Remove 'v' string
        id: remove_prefix_from_tag
        run: |
          VERSION=$(echo  ${{ github.ref_name }} | sed "s/v//")
          echo SEMVER_VERSION=$VERSION>> $GITHUB_ENV

      - name: Print Semver Version
        run: echo ${{ env.SEMVER_VERSION }}

      - name: log
        if: ${{ startsWith(github.ref, 'refs/tags/v') }}
        run: |
          echo "Tag name from GITHUB_REF_NAME: $GITHUB_REF_NAME"
          echo "Tag name from github.ref_name: ${{  github.ref_name }}"
          echo version_tag github.ref ${{ github.ref }}
          echo SemverVersion: env.SEMVER_VERSION
