# This is a basic workflow that is manually triggered

name: Deploy

# Controls when the action will run. Workflow runs when manually triggered using the UI
# or API.
on:
  push:
    tags:
      - v*

  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  deploy-dev:
    name: Dev
    runs-on: ubuntu-latest
    steps: 
      - name: Echo
        run: echo dev
  deploy-stage:
    needs: deploy-dev
    name: Stage
    environment: Stage
    runs-on: ubuntu-latest
    steps: 
      - name: Echo
        run: echo stage
  deploy-prod:
    needs: deploy-stage
    environment: Production
    name: Prod
    runs-on: ubuntu-latest
    steps: 
      - name: Echo
        run: echo prod
    
