# This is a basic workflow that is manually triggered

name: Deploy

# Controls when the action will run. Workflow runs when manually triggered using the UI
# or API.
# on:
#   workflow_run:
#     workflows: [Build]
#     types:
#       - completed
on: [workflow_dispatch]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  semver:
    runs-on: ubuntu-latest
    steps:
      - name: Remove 'v' from git tag
        id: remove_prefix_from_tag
        run: echo "SEMVER_VERSION=$( ${{ github.ref_name }} | sed "s/v//") "  >> $GITHUB_ENV
      - name: Print Semver Version
        run: echo ${{ env.SEMVER_VERSION }}

      - name: log
        if: ${{ startsWith(github.ref, 'refs/tags/v') }}
        run: |
          echo "Tag name from GITHUB_REF_NAME: $GITHUB_REF_NAME"
          echo "Tag name from github.ref_name: ${{  github.ref_name }}"
          echo version_tag github.ref ${{ github.ref }}
